### ISSUE TITLE
Touch Bar Support

### ISSUE THREAD

**Issue by ApolloZhu** [ApolloZhu/Dynamic#4]
I don't have a Touch Bar...

**Comment by CaptainYukinoshitaHachiman** [comment]
So what are you going to do with a Touch Bar?

**Comment by ApolloZhu** [comment]
1. That toggle button in the menu bar...

When settings panel is visible
2. Map settings to Touch Bar actions

**Comment by ApolloZhu** [comment]
Thank you for your suggestions, but Xcode does have a Touch Bar simulator built in. My main concern is that my design is not what the Touch Bar users are familiar with, as I have never used it before.

**Comment by AutinMitra** [comment]
I would add the toggle button to the control strip (can be accessed via private FW: [](https://stackoverflow.com/questions/47988940/adding-button-to-nstouchbar-control-strip "NSTouchbar System Tray"). The only problem would be confusion with the brightness icon, but that can be fixed by using color for the touch bar icon. I wouldn't use the middle section of it for toggling, but maybe for adjusting preferences.

**Comment by AutinMitra** [comment]
My spaghetti code ([DarkM](https://github.com/AutinMitra/DarkM)) has the toggle from the TouchBar, should be easy to implement in Dynamic.
